# Generated by Django 3.1.4 on 2021-05-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0002_auto_20210514_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
