# Generated by Django 3.1.4 on 2021-05-14 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0003_jobpost_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='entry_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
