# Generated by Django 3.1.4 on 2021-05-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0004_auto_20210514_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('hourly_rate', models.CharField(blank=True, max_length=255)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('doc_upload', models.FileField(blank=True, upload_to='')),
                ('tag', models.CharField(blank=True, max_length=255)),
                ('intro', models.TextField(blank=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_description',
            field=models.TextField(blank=True),
        ),
    ]
