# Generated by Django 3.1.4 on 2021-05-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0006_auto_20210515_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='account_type',
            new_name='account_type1',
        ),
        migrations.AddField(
            model_name='profile',
            name='account_type2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
