# Generated by Django 3.1.4 on 2021-05-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0007_auto_20210515_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='account_type1',
            new_name='account_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='account_type2',
        ),
    ]
