# Generated by Django 3.1.4 on 2021-05-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0008_auto_20210515_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_category',
            field=models.CharField(choices=[('Web & Software Dev', 'Web & Software Dev'), ('Data Science & Analitycs', 'Data Science & Analitycs'), ('Networking', 'Networking'), ('Support specialist', 'Support specialist'), ('Tester', 'Tester'), ('Analyst', 'Analyst'), ('User experience designer', 'User experience designer'), ('Tester', 'Tester')], max_length=100),
        ),
    ]
