# Generated by Django 3.2.3 on 2021-06-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0011_auto_20210515_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
