# Generated by Django 3.2.3 on 2021-06-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0017_alter_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
