# Generated by Django 3.2.3 on 2021-06-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0018_auto_20210603_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
