# Generated by Django 3.2.3 on 2021-06-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0020_profile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role1', models.CharField(blank=True, max_length=255)),
                ('company1', models.CharField(blank=True, max_length=255)),
                ('period1', models.CharField(blank=True, max_length=255)),
                ('job_role2', models.CharField(blank=True, max_length=255)),
                ('company2', models.CharField(blank=True, max_length=255)),
                ('period2', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'employment',
            },
        ),
    ]
