# Generated by Django 3.2.3 on 2021-06-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0021_employement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employement',
            old_name='period1',
            new_name='period1a',
        ),
        migrations.RenameField(
            model_name='employement',
            old_name='period2',
            new_name='period1b',
        ),
        migrations.AddField(
            model_name='employement',
            name='period2a',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employement',
            name='period2b',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
