# Generated by Django 3.2.3 on 2021-06-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0022_auto_20210605_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='employement',
            name='duty1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employement',
            name='duty2',
            field=models.TextField(blank=True),
        ),
    ]
