# Generated by Django 3.2.3 on 2021-06-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0023_auto_20210605_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employement',
            name='company2',
        ),
        migrations.RemoveField(
            model_name='employement',
            name='duty2',
        ),
        migrations.RemoveField(
            model_name='employement',
            name='job_role2',
        ),
        migrations.RemoveField(
            model_name='employement',
            name='period2a',
        ),
        migrations.RemoveField(
            model_name='employement',
            name='period2b',
        ),
        migrations.AddField(
            model_name='company',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='duty',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='end_period',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='job_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='start_period',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
