# Generated by Django 3.2.3 on 2021-06-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0025_remove_profile_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='duty',
        ),
        migrations.RemoveField(
            model_name='company',
            name='end_period',
        ),
        migrations.RemoveField(
            model_name='company',
            name='job_role',
        ),
        migrations.RemoveField(
            model_name='company',
            name='start_period',
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='duty',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='end_period',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_period',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
