# Generated by Django 3.2.3 on 2021-06-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0026_auto_20210605_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employement',
            name='period1a',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employement',
            name='period1b',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='end_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
