# Generated by Django 3.2.3 on 2021-06-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0027_auto_20210605_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
