# Generated by Django 3.2.3 on 2021-06-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0029_auto_20210605_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
