# Generated by Django 3.2.3 on 2021-06-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0031_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='end_period',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_period',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
