# Generated by Django 3.2.3 on 2021-06-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0032_auto_20210605_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techjobi.jobpost')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
