# Generated by Django 3.2.3 on 2021-06-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0033_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_post',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
