# Generated by Django 3.2.3 on 2021-06-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0034_alter_application_job_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='application_view',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_view',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
