# Generated by Django 3.2.3 on 2021-06-07 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0042_auto_20210607_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='entry_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
