# Generated by Django 3.2.3 on 2021-06-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techjobi', '0043_auto_20210607_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Expired', 'Expired')], default='Pending Approval', max_length=50),
        ),
    ]
